#!/bin/sh

### BEGIN INIT INFO
# Required-Start: $network $remote_fs $syslog
# Required-Stop: $network $remote_fs $syslog
# Default-Start: 3 5
# Default-Stop: 1 6
# Description: (suse) Start artemis program run control
### END INIT INFO
# chkconfig: 35 99 99
# description: (suse) Start artemis program run control

# ss5 sschwigo 2008-09-29 TODO: that's a dirty hack
# mount natrium:/vol/osrc_home/ /home

#needed for NFS
if [[ -e /etc/init.d/portmap ]]
then
	/etc/init.d/portmap start
fi


STARTSCRIPT=
FILENAME="artemis-automatic-test.pl"
POSSIBLE_PATHS="
/mnt/opt/artemis/bin/
/opt/artemis/bin/
/home/artemis/perl510/bin/
"

for(( i=0; i<10; i++))
do
    ping -c1 bancroft > /dev/null && break
    echo "wait for network available..."
    sleep 2
done


mount natrium:/vol/osrc_home/ /home
for DIR in $POSSIBLE_PATHS; do
    STARTSCRIPT=${DIR}/$FILENAME
    if [[ -e $STARTSCRIPT ]]
    then
        /sbin/ifconfig
        ${DIR}/perl $STARTSCRIPT $*
        exit 0
    fi
done

