#!/bin/sh

### BEGIN INIT INFO
# Required-Start:  $ALL
# Default-Start: 3 5 
# Default-Stop: 1 6
# Description: (redhat) Start artemis program run control
### END INIT INFO
# chkconfig: 35 99 99
# description: (redhat) Start artemis program run control

#needed for NFS
if [[ -e /etc/init.d/portmap ]]
then
	/etc/init.d/portmap start
fi

STARTSCRIPT=
FILENAME="artemis-automatic-test.pl"
POSSIBLE_PATHS="
/mnt/opt/artemis/bin/
/opt/artemis/bin/
/home/artemis/perl510/bin/
"
while (( 1 )); do
    for DIR in $POSSIBLE_PATHS; do
        STARTSCRIPT=${DIR}/$FILENAME
        if [[ -e $STARTSCRIPT ]]
        then
            /sbin/ifconfig
            ${DIR}/perl $STARTSCRIPT $*
            exit 0
        fi
    done
    mount natrium:/vol/osrc_home/ /home
    echo "Wait for auto mount /home/artemis ..."
    sleep 2
done


